[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/buger/jsonparser"

[[constraint]]
  name = "github.com/carlosdp/twiliogo"
  version = "0.1.0"

[[constraint]]
  name = "github.com/valyala/fasthttp"
  version = "20160617.0.0"

[prune]
  go-tests = true
  unused-packages = true
